import { Refine } from '@refinedev/core';
import './global.css';

export const metadata = {
  title: 'Welcome to nx-refine',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Refine
          resources={[
            {
              name: 'products',
              list: '/my-products',
              show: '/my-products/:id',
              edit: '/my-products/:id/edit',
              create: '/my-products/new',
            },
          ]}
        >
          {children}
        </Refine>
      </body>
    </html>
  );
}
